name: Dump
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://in-sysup-txdl.vivoglobal.com/upgrade/official/officialFiles/PD1928F_EX_A_1.70.12-update-full_1634208097.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              git clone https://github.com/HyperNotAryanX97/phoenix_firmware_dumper firmware_dumper
           
       - name: Setup Dumpyara environment
         working-directory: firmware_dumper
         run: |
              sudo bash setup.sh
              git config --global user.name "flashokillerify"
              git config --global user.email "flashokiller@gmail.com"

       - name: Setup config envs
         working-directory: firmware_dumper
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.GITORGNAME }}" > .git_orgname
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Running Dumpyara
         working-directory: firmware_dumper
         run: |
              ./dumper.sh  "$ROM_URL"

#haha QCOM
