name: Dump
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://dropmirror.bahacec.workers.dev/0:/Vivo_U10_PD1928F_EX_A_1.9.3_LA.UM.7.11.r1-01300-NICOBAR.0-sm6125_split_QPST_%28by_vivofirmware.com%29.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              git clone https://github.com/HyperNotAryanX97/phoenix_firmware_dumper
               ls
       - name: Setup Dumpyara environment
         working-directory: phoenix_firmware_dumper
         run: |
              sudo bash setup.sh
              git config --global user.name "flashokiller"
              git config --global user.email "flashokiller@gmail.com"

       - name: Setup config envs
         working-directory: phoenix_firmware_dumper
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.GITORGNAME }}" > .git_orgname
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Running Dumpyara
         working-directory: phoenix_firmware_dumper
         run: |
              ./dumper.sh  "$ROM_URL"

#haha Meme tek
